# Generated by Django 6.0 on 2025-12-11 01:15

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=0, max_digits=10)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion_local', models.CharField(help_text='Ej: Edificio ML, Piso 3', max_length=100)),
                ('celular_pedidos', models.CharField(help_text='Número WhatsApp para recibir pedidos (10 dígitos)', max_length=10, validators=[django.core.validators.RegexValidator(message='Debe ser un número celular colombiano válido.', regex='^3\\d{9}$')])),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo institucional')),
                ('codigo_estudiante', models.CharField(help_text='Código único de la Universidad de los Andes', max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='El código debe tener exactamente 9 dígitos numéricos (Ej: 202512752)', regex='^\\d{9}$')])),
                ('nombre_completo', models.CharField(max_length=150)),
                ('celular', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Debe ser un número celular colombiano válido (10 dígitos, empieza por 3).', regex='^3\\d{9}$')])),
                ('rol', models.CharField(choices=[('ESTUDIANTE', 'Estudiante'), ('PROFESOR', 'Profesor'), ('REPARTIDOR', 'Repartidor (Equipo)'), ('ADMIN', 'Administrador')], default='ESTUDIANTE', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edificio_entrega', models.CharField(help_text='Ej: Edificio W', max_length=50)),
                ('detalle_ubicacion', models.CharField(help_text='Ej: Portería principal o Salón 201', max_length=100)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago'), ('VERIFICANDO', 'Verificando Transferencia'), ('EN_COCINA', 'Aprobado - En Cocina'), ('EN_CAMINO', 'En Camino'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('total_pagar', models.DecimalField(decimal_places=0, max_digits=10)),
                ('costo_domicilio', models.DecimalField(decimal_places=0, default=2000, max_digits=10)),
                ('evidencia_pago_url', models.CharField(blank=True, max_length=255, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=0, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='core.restaurante'),
        ),
    ]
