# Generated by Django 6.0 on 2025-12-11 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='codigo_verificacion',
            field=models.CharField(blank=True, help_text='Código temporal de 6 dígitos enviado al correo', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verificado',
            field=models.BooleanField(default=False, help_text='¿El usuario ya confirmó su correo institucional?'),
        ),
    ]
