# Generated by Django 6.0 on 2025-12-13 12:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_detallepedido_precio_unitario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='evidencia_pago_url',
        ),
        migrations.AddField(
            model_name='pedido',
            name='comprobante_pago',
            field=models.ImageField(blank=True, help_text='Sube aquí el pantallazo de Nequi/DaviPlata', null=True, upload_to='comprobantes/'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='detalle_ubicacion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='edificio_entrega',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='celular_pedidos',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='ubicacion_local',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='celular',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Debe ser un número celular colombiano válido.', regex='^3\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='codigo_estudiante',
            field=models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='El código debe tener exactamente 9 dígitos numéricos', regex='^\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='codigo_verificacion',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verificado',
            field=models.BooleanField(default=False),
        ),
    ]
