# Generated by Django 6.0 on 2025-12-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_pedido_evidencia_pago_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='jornada_entrega',
            field=models.CharField(choices=[('12:00 - 12:45', 'Almuerzo Temprano (12:00 - 12:45)'), ('12:45 - 13:30', 'Almuerzo Pico (12:45 - 1:30)'), ('13:30 - 14:15', 'Almuerzo Tarde (1:30 - 2:15)')], default='12:45 - 13:30', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(choices=[('NORMAL', 'Normal (Sin costo extra)'), ('PRIORITARIA', '⚡ Prioritaria (+$2.000)'), ('FLEXIBLE', '🐢 Flexible/Espera (-$1.000)')], default='NORMAL', max_length=20),
        ),
    ]
