# Generated by Django 6.0 on 2026-01-15 03:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pedido_jornada_entrega_pedido_tipo_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='propina',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='repartidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='comprobante_pago',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes/'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('PRIORITARIA', '⚡ Flash (+$2.000)'), ('FLEXIBLE', '🐢 Relax (-$1.000)')], default='NORMAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='celular',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Debe ser celular válido.', regex='^3\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='codigo_estudiante',
            field=models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='El código debe tener exactamente 9 dígitos', regex='^\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('ESTUDIANTE', 'Estudiante (Cliente)'), ('ASPIRANTE', 'Aspirante a Domiciliario'), ('REPARTIDOR', 'Repartidor Autorizado'), ('ADMIN', 'Administrador')], default='ESTUDIANTE', max_length=20),
        ),
    ]
